FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG DOCS_TITLE="API Documentation"
ARG DOCS_DESCRIPTION="Official API documentation"
ARG DOCS_VERSION="v1"
ARG DOCS_BASE_PATH="/"
ARG DOCS_LOGO="/assets/logo.svg"
ARG DOCS_LOGO_DARK="/assets/logo-dark.svg"
ARG DOCS_LOGO_ALT="API Documentation"
ARG DOCS_API_DEV_URL="https://dev-api.example.com"
ARG DOCS_API_STAGING_URL="https://staging-api.example.com"
ARG DOCS_API_PROD_URL="https://api.example.com"
ARG DOCS_DEFAULT_ENV="production"
ARG DOCS_ENABLE_TRY_IT="true"
ARG DOCS_TRY_IT_ALLOW_CUSTOM_BASE_URL="false"
ARG DOCS_TRY_IT_PROXY_URL=""
ARG DOCS_VISIBILITY="public"

ENV DOCS_TITLE=$DOCS_TITLE
ENV DOCS_DESCRIPTION=$DOCS_DESCRIPTION
ENV DOCS_VERSION=$DOCS_VERSION
ENV DOCS_BASE_PATH=$DOCS_BASE_PATH
ENV DOCS_LOGO=$DOCS_LOGO
ENV DOCS_LOGO_DARK=$DOCS_LOGO_DARK
ENV DOCS_LOGO_ALT=$DOCS_LOGO_ALT
ENV DOCS_API_DEV_URL=$DOCS_API_DEV_URL
ENV DOCS_API_STAGING_URL=$DOCS_API_STAGING_URL
ENV DOCS_API_PROD_URL=$DOCS_API_PROD_URL
ENV DOCS_DEFAULT_ENV=$DOCS_DEFAULT_ENV
ENV DOCS_ENABLE_TRY_IT=$DOCS_ENABLE_TRY_IT
ENV DOCS_TRY_IT_ALLOW_CUSTOM_BASE_URL=$DOCS_TRY_IT_ALLOW_CUSTOM_BASE_URL
ENV DOCS_TRY_IT_PROXY_URL=$DOCS_TRY_IT_PROXY_URL
ENV DOCS_VISIBILITY=$DOCS_VISIBILITY

RUN npm run validate:docs
RUN npm run build

FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
